#!/usr/bin/env bash

PRIMARY="HDMI-1"
SECONDARY="HDMI-2"

NATIVE_MODE="1920x1080@119.993"
STRETCHED_MODE="1440x1080@119.925"

SECONDARY_MODE="1920x1080@74.973"

NATIVE_RES="${NATIVE_MODE%@*}"
CURRENT_RES=$(gnome-monitor-config list | grep "PRIMARY" | cut -d " " -f 4 | cut -d '+' -f 1)

if [[ "$CURRENT_RES" == "$NATIVE_RES" ]]; then
  echo "Switching to stretched $STRETCHED_MODE..."
  gnome-monitor-config set \
    -LpM "$PRIMARY" -m "$STRETCHED_MODE" -t normal \
    -LM "$SECONDARY" -m "$SECONDARY_MODE" -x 1440 -y 0 -t normal
else
  echo "Switching to native $NATIVE_MODE..."
  gnome-monitor-config set \
    -LpM "$PRIMARY" -m "$NATIVE_MODE" -t normal \
    -LM "$SECONDARY" -m "$SECONDARY_MODE" -x 1920 -y 0 -t normal
fi
